name: scrape

on:
  schedule:
    - cron: 0 0 * * *

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: prod
      deployment: false
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
      - run: go test -v -run ^TestScraping$ ./...
        env:
          TEST_SCRAPING: true
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
