name: tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  actions: read
  attestations: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
          cache: false
      - run: |
          go test -gcflags="all=-N -l" -p 1 -v -timeout 30s ./...
        env:
          XDG_MUSIC_DIR: /tmp
  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    environment:
      name: prod
      deployment: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
          cache: false
      - run: |
          go mod download
          for os in linux darwin windows; do
            for arch in arm64 amd64; do
              fname="spotitube-${os}-${arch}"
              if test "${os}" = "windows"; then
                fname="${fname}.exe"
              fi
              echo "building $fname..."
              GOOS=$os GOARCH=$arch CGO_ENABLED=0 go build -ldflags="-s -w
                -X github.com/streambinder/spotitube/spotify.fallbackSpotifyID=$SPOTIFY_ID
                -X github.com/streambinder/spotitube/spotify.fallbackSpotifyKey=$SPOTIFY_KEY
                -X github.com/streambinder/spotitube/lyrics.fallbackGeniusToken=$GENIUS_TOKEN
              " -o "$fname"
            done
          done
        env:
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          SPOTIFY_KEY: ${{ secrets.SPOTIFY_KEY }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
      - run: gh release create "$REF_NAME" ./spotitube-* --draft=false --prerelease=false
        env:
          REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.RELEASE_SPOTITUBE }}
  docker:
    runs-on: ubuntu-24.04-arm
    needs: [test]
    if: success()
    environment:
      name: prod
      deployment: false
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
        with:
          secrets: |
            SPOTIFY_ID=${{ secrets.SPOTIFY_ID }}
            SPOTIFY_KEY=${{ secrets.SPOTIFY_KEY }}
            GENIUS_TOKEN=${{ secrets.GENIUS_TOKEN }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}:release
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          push: true
